Factory/Models/DesignTimeDBContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;
using System; 
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
    public class Engineer
    {
        public Engineer()
        {
            this.JoinEntities = new HashSet<EngineerMachine>();
        }

        public int EngineerId { get; set; }
        public string Name { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "License Date")]
        public DateTime LicenseDate { get; set; }
        [Display(Name = "Actively working on Repairs")]
        public bool Repairs { get; set; }

        public virtual ICollection<EngineerMachine> JoinEntities { get;}
    }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
    {       
        public int EngineerMachineId { get; set; }
        public int EngineerId { get; set; }
        public int MachineId { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual Engineer Engineer { get; set; }
    }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Machine> Machines { get; set; }
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<EngineerMachine> EngineerMachine { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System; 
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public string Name{ get; set; }
    public int MachineId { get; set; }    
    [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
    [Display(Name = "Inspection Date")]
    public DateTime InspectionDate { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set ;}
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
          .Include(engineer => engineer.JoinEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
          .Include(machine => machine.JoinEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@model Factory.Models.Engineer

<h2>Add a machine</h2>

<h4>Add a machine to this task: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select machine")
    @Html.DropDownList("MachineId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Engineers/Create.cshtml
@model Factory.Models.Engineer

<h4>Add a new Engineer</h4>

@using (Html.BeginForm())
{
    <p>@Html.LabelFor(model => model.Name, new{ required = "required" })
    @Html.TextBoxFor(model => model.Name, new{ required = "required" })</p>

    <p>@Html.LabelFor(model => model.LicenseDate)
    @Html.TextBoxFor(model => model.LicenseDate, "{0:yyyy-MM-dd}", new { @placeholder = "YYYY-MM-DD" })</p>

    <p>@Html.LabelFor(model => model.Repairs, new{ required = "required" })
    @Html.CheckBoxFor(model => model.Repairs, new{ required = "required" })</p>

    <p>@Html.Label("Select machine")
    @Html.DropDownList("MachineId")</p>

    <input type="submit" value="Add new engineer" class="btn btn-default" />
}
<p>@Html.ActionLink("List of Engineers", "Index")</p>

Factory/Views/Engineers/Delete.cshtml
@model Factory.Models.Engineer

<h2>Are you sure you want to delete this Engineer?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Engineers/Details.cshtml
@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.LicenseDate): @Html.DisplayFor(model => model.LicenseDate)</h3>
<h3>@Html.DisplayNameFor(model => model.Repairs): @Html.DisplayFor(model => model.Repairs)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This engineer does not belong to any machines</p>
}
else
{
  <h4>Machines the Engineer belongs to:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Machine.Name</li>
    @using (Html.BeginForm("DeleteMachine", "Engineers"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Back to list of Engineers", "Index")</p>
<p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Edit.cshtml
@model Factory.Models.Engineer

<h2>Edit an Engineer</h2>

<h4>Editing: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    <p>@Html.LabelFor(model => model.LicenseDate)
    @Html.TextBoxFor(model => model.LicenseDate, "{0:yyyy-MM-dd}", new { @placeholder = "YYYY-MM-DD" })</p>

    <p>@Html.LabelFor(model => model.Repairs)
    @Html.CheckBoxFor(model => model.Repairs)</p>

    <p>@Html.Label("Select machine")
    @Html.DropDownList("MachineId")</p>

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Engineers/Index.cshtml
@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h1>Engineers</h1>

@if (@Model.Count == 0)
{
  <h3>No engineers have been added yet!</h3>
} 

<ul>
  @foreach(Engineer engineer in Model)
  {  
    <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new engineer", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Home/Index.cshtml
<h1>Welcome to SillyStringz!</h1>
<p>@Html.ActionLink("See all Engineers", "Index", "Engineers")</p>
<p>@Html.ActionLink("See all Machines", "Index", "Machines")</p>

Factory/Views/Machines/Create.cshtml
@model Factory.Models.Machine

<h4>Add a new Machine</h4>

@using (Html.BeginForm())
{
    <p>@Html.LabelFor(model => model.Name, new{ required = "required" })
    @Html.TextBoxFor(model => model.Name, new{ required = "required" })</p>

    <p>@Html.LabelFor(model => model.InspectionDate)
    @Html.TextBoxFor(model => model.InspectionDate, "{0:yyyy-MM-dd}", new { @placeholder = "YYYY-MM-DD" })</p>

    <input type="submit" value="Add new machine" class="btn btn-default" />
}
<p>@Html.ActionLink("List of Machines", "Index")</p>

Factory/Views/Machines/Delete.cshtml
@model Factory.Models.Machine

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Machines/Details.cshtml
@model Factory.Models.Machine;

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.InspectionDate): @Html.DisplayFor(model => model.InspectionDate)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This machine does not have any engineers</p>
}
else
{
  <h4>Engineers with this machine:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Engineer.Name</li>
  }
  </ul>
}

<p>@Html.ActionLink("Back to machines", "Index")</p>
<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Edit.cshtml
@model Factory.Models.Machine

<h2>Edit a Machine</h2>

<h4>Editing: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  <p>@Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)</p>

  <p>@Html.LabelFor(model => model.InspectionDate)
  @Html.TextBoxFor(model => model.InspectionDate, "{0:yyyy-MM-dd}", new { @placeholder = "YYYY-MM-DD" })</p>

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Index.cshtml
@using Factory.Models;

<h1>Machines</h1>

@if (@Model.Count == 0)
{
  <h3>No machines have been added yet!</h3>
} 

<ul>
  @foreach(Machine machine in Model)
  {
    <li>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new machine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Shared/_Footer.cshtml
<div id="footer">Albert Lee, Epicodus 2021</div>

Factory/Views/Shared/_Header.cshtml
<nav>
  <ul id="nav-ul">
    <li class="nav-li-start">@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="nav-li">@Html.ActionLink("Engineers", "Index", "Engineers")</li>
    <li class="nav-li">@Html.ActionLink("Machines", "Index", "Machines")</li>
  </ul>
</nav>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>SillyStringz!</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css">
</head>
<div class="container">

  <body>
    @await Html.PartialAsync("_Header")
    @RenderBody()
    @await Html.PartialAsync("_Footer")
  </body>
</div>

</html>